// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKuhpEBxCaPQxWBZf9gszHPKvsU1_NGUI',
    appId: '1:446993648494:web:ca2d5ace2010118d9c8f7f',
    messagingSenderId: '446993648494',
    projectId: 'group-bills-dcce3',
    authDomain: 'group-bills-dcce3.firebaseapp.com',
    storageBucket: 'group-bills-dcce3.appspot.com',
    measurementId: 'G-33DEMHB1WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8XF2mW8AiP8TLlptOZk_odcM7-0KkQM',
    appId: '1:446993648494:android:d7cd4fd392689c669c8f7f',
    messagingSenderId: '446993648494',
    projectId: 'group-bills-dcce3',
    storageBucket: 'group-bills-dcce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5yoDFDCuVsowZ350WffhXONnXyg4yoaQ',
    appId: '1:446993648494:ios:321346097adb10e69c8f7f',
    messagingSenderId: '446993648494',
    projectId: 'group-bills-dcce3',
    storageBucket: 'group-bills-dcce3.appspot.com',
    androidClientId: '446993648494-f9bhru5mho48l1gvi0osfc957d70177p.apps.googleusercontent.com',
    iosClientId: '446993648494-uk07rutseq438dq02do447pqpr4bt769.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupBills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5yoDFDCuVsowZ350WffhXONnXyg4yoaQ',
    appId: '1:446993648494:ios:321346097adb10e69c8f7f',
    messagingSenderId: '446993648494',
    projectId: 'group-bills-dcce3',
    storageBucket: 'group-bills-dcce3.appspot.com',
    androidClientId: '446993648494-f9bhru5mho48l1gvi0osfc957d70177p.apps.googleusercontent.com',
    iosClientId: '446993648494-uk07rutseq438dq02do447pqpr4bt769.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupBills',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKuhpEBxCaPQxWBZf9gszHPKvsU1_NGUI',
    appId: '1:446993648494:web:3e20ec78c618984c9c8f7f',
    messagingSenderId: '446993648494',
    projectId: 'group-bills-dcce3',
    authDomain: 'group-bills-dcce3.firebaseapp.com',
    storageBucket: 'group-bills-dcce3.appspot.com',
    measurementId: 'G-HPBE54T7XZ',
  );
}
